### ISSUE TITLE
Refactor Multispend Prototype to use Fedimint & Supabase Realtime

### ISSUE THREAD

**Issue by IroncladDev** [fedibtc/Multispend#1]
The Multispend prototype is using express/socketIO as a backend, which is not a good solution for a hosted project on Vercel.

Migrating to use Supabase Realtime and use Fedimint instead of LNBits.

**Comment by IroncladDev** [comment]
According to @Kodylow, we will start focusing on developing more Fedi Mods in a couple months.

I will start working on this ticket when the time comes, which is after a considerable amount of upcoming sprints.

@bprice6 should I close this one for now or should I just leave it in Blocked?

**Comment by Kodylow** [comment]
Negative, MultiSpend is a high priority Fedi mod according to obi but it's been pending product specifications and a PRD.

The "couple months from now" was in reference to when we were going to be building more using mods generally as a platform on Fedi after we have the webln/nostr/ecash integrations improved. MultiSpend specifically was listed as high priority.

**Comment by bprice6** [comment]
Let's stick to the tickets in `queue` until some of these get unblocked. Thanks!

**Comment by bprice6** [comment]
As added context we're chatting with some NGO's if they're willing to do a manual workaround. Waiting to hear back.

**Comment by IroncladDev** [comment]
I'm tracking this one, split into two different tickets:

Frontend: https://github.com/fedibtc/Multispend/issues/2
Backend: https://github.com/fedibtc/Multispend/issues/3

As of this comment, they are blocked (waiting on some designs and other stuff). I'll work on what I can to get this unblocked.
